[package]
name = "software1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "week2"
path = "src/week2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
